# [START example-app]
runtime: nodejs14

handlers:
  # Serve all static files with urls ending with a file extension
- url: /(.*\..+)$ 
  static_files: dist/\1
  upload: dist/(.*\..+)$
  # catch all handler to index.html
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html

instance_class: B1

basic_scaling:
  max_instances: 2
  idle_timeout: 10m
